"""baseline schema

Migration de reference generee par `alembic revision --autogenerate` a partir
de app/domains/*/models.py (une fois env.py corrige pour importer tous les
domaines - voir commentaire dans env.py). Elle reproduit fidelement le schema
deja applique en production via db/migrations/001_init.sql a 007_backtest_metrics.sql
(verifie table par table dans un Postgres jetable : les 16 tables ORM
correspondent exactement).

Ne remplace PAS db/migrations/*.sql pour les installations Docker Compose
existantes (docker-entrypoint-initdb.d continue de bootstrapper depuis ces
fichiers au premier demarrage d'un volume vide, comme documente dans
docker-compose.yml). Cette migration sert de point de depart Alembic pour :
- les environnements sans Docker (`alembic upgrade head` sur une base vide,
  ex. tests, dev local) ;
- toute evolution future du schema, qui doit desormais passer par
  `alembic revision --autogenerate` plutot que par un nouveau fichier
  db/migrations/*.sql (intention deja documentee dans docker-compose.yml,
  jamais suivie en pratique jusqu'ici puisque cette migration de base
  n'existait pas).

Difference volontaire avec le SQL brut : les colonnes UUID n'ont pas de
`DEFAULT uuid_generate_v4()` cote base - les modeles SQLAlchemy generent
l'UUID cote Python (`default=uuid.uuid4`), donc l'extension "uuid-ossp"
n'est pas necessaire pour les installations qui partent de cette migration.

La table `compliance_audit_log` (definie dans 001_init.sql) n'apparait pas
ici : aucun modele SQLAlchemy ne la mappe, elle n'est lue ni ecrite par le
code actuel (verifie par recherche globale). A traiter comme dette technique
documentee dans docs/STACK.md, pas corrige ici pour ne pas inventer une
fonctionnalite d'audit non demandee.

Revision ID: 0001
Revises:
Create Date: 2026-07-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'market', name='uq_asset_ticker_market')
    )
    op.create_index(op.f('ix_assets_market'), 'assets', ['market'], unique=False)
    op.create_index(op.f('ix_assets_sector'), 'assets', ['sector'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('asset_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analyst_consensus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('strong_sell', sa.Integer(), nullable=False),
    sa.Column('consensus_score', sa.Float(), nullable=False),
    sa.Column('consensus_label', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_consensus_asset_id'), 'analyst_consensus', ['asset_id'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('precision', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('false_positive_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_risk_reward', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_backtest_run_id'), 'backtest_results', ['backtest_run_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_method', sa.String(length=50), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_asset_id'), 'news_articles', ['asset_id'], unique=False)
    op.create_table('notification_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('last_notified_signal', sa.String(length=30), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'horizon', name='uq_notification_state_asset_horizon')
    )
    op.create_index(op.f('ix_notification_states_asset_id'), 'notification_states', ['asset_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_asset_id'), 'portfolio_positions', ['asset_id'], unique=True)
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('slippage_amount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_transactions_asset_id'), 'portfolio_transactions', ['asset_id'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'trade_date', name='uq_price_bar_asset_date')
    )
    op.create_index(op.f('ix_price_bars_asset_id'), 'price_bars', ['asset_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('news_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('final_signal', sa.String(length=30), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_asset_id'), 'signals', ['asset_id'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sma_200', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ema_12', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ema_26', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bollinger_upper', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bollinger_lower', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volatility_20d', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('momentum_roc_20', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'trade_date', name='uq_indicator_asset_date')
    )
    op.create_index(op.f('ix_technical_indicators_asset_id'), 'technical_indicators', ['asset_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('notify_on_change', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_asset_id'), 'watchlist_items', ['asset_id'], unique=True)
    op.create_table('news_keyword_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('horizon_impact', sa.String(length=20), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_keyword_matches_article_id'), 'news_keyword_matches', ['article_id'], unique=False)
    op.create_table('signal_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('contribution_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('text_explanation', sa.Text(), nullable=False),
    sa.Column('supporting_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_explanations_signal_id'), 'signal_explanations', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_explanations_signal_id'), table_name='signal_explanations')
    op.drop_table('signal_explanations')
    op.drop_index(op.f('ix_news_keyword_matches_article_id'), table_name='news_keyword_matches')
    op.drop_table('news_keyword_matches')
    op.drop_index(op.f('ix_watchlist_items_asset_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_technical_indicators_asset_id'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_signals_asset_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_price_bars_asset_id'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_portfolio_transactions_asset_id'), table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_positions_asset_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_notification_states_asset_id'), table_name='notification_states')
    op.drop_table('notification_states')
    op.drop_index(op.f('ix_news_articles_asset_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_backtest_results_backtest_run_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_analyst_consensus_asset_id'), table_name='analyst_consensus')
    op.drop_table('analyst_consensus')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('portfolio_state')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_sector'), table_name='assets')
    op.drop_index(op.f('ix_assets_market'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
